'use client';

import { FormEvent, useEffect, useState } from 'react';
import { CopyPlus, ShieldCheck } from 'lucide-react';
import { PERMISSION_DEFINITIONS, type AdminPermission } from '@/lib/admin/permissions';

type Role = { id: number; code: string; name: string; description: string; permissions: AdminPermission[]; isSystem: boolean; status: number };

export default function AdminRolesPage() {
  const [roles, setRoles] = useState<Role[]>([]);
  const [code, setCode] = useState(''); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [permissions, setPermissions] = useState<AdminPermission[]>([]); const [message, setMessage] = useState('');
  const load = async () => { const response = await fetch('/api/admin/roles'); const payload = await response.json(); if (payload.success) setRoles(payload.data); };
  useEffect(() => { load().catch(() => setMessage('Khong the tai vai tro.')); }, []);
  const toggle = (permission: AdminPermission) => setPermissions((current) => current.includes(permission) ? current.filter((item) => item !== permission) : [...current, permission]);
  const clone = (role: Role) => { setCode(`${role.code}_copy`); setName(`${role.name} copy`); setDescription(role.description); setPermissions(role.permissions.filter((permission) => permission !== '*')); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(''); const response = await fetch('/api/admin/roles', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: window.location.origin }, body: JSON.stringify({ code, name, description, permissions }) }); const payload = await response.json(); if (!response.ok || !payload.success) { setMessage(payload?.error?.message || 'Khong the tao vai tro'); return; } setCode(''); setName(''); setDescription(''); setPermissions([]); await load(); setMessage('Da tao vai tro tuy chinh.'); };
  return <div className="mx-auto max-w-7xl space-y-6"><div><p className="text-xs font-mono text-red-400">ROLE TEMPLATES</p><h1 className="text-2xl font-black text-white">Vai tro va quyen</h1></div><form onSubmit={submit} className="rounded-xl border border-gray-800 bg-gray-950/50 p-5 space-y-4"><div className="grid gap-3 md:grid-cols-3"><input value={code} onChange={(event) => setCode(event.target.value)} placeholder="role_code" required className="rounded-lg border border-gray-700 bg-black/40 px-3 py-2.5 text-sm" /><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Ten vai tro" required className="rounded-lg border border-gray-700 bg-black/40 px-3 py-2.5 text-sm" /><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Mo ta" className="rounded-lg border border-gray-700 bg-black/40 px-3 py-2.5 text-sm" /></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{PERMISSION_DEFINITIONS.filter((item) => !item.systemOnly).map((definition) => <div key={definition.resource} className="rounded border border-gray-800 p-3"><p className="mb-2 text-xs font-bold text-gray-300">{definition.label}</p>{definition.actions.map((action) => { const permission = `${definition.resource}.${action}` as AdminPermission; return <label key={permission} className="mr-3 text-xs text-gray-400"><input type="checkbox" checked={permissions.includes(permission)} onChange={() => toggle(permission)} /> {action}</label>; })}</div>)}</div>{message ? <p className="text-sm text-red-300">{message}</p> : null}<button className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-red-500"><CopyPlus className="h-4 w-4" />Tao vai tro tuy chinh</button></form><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{roles.map((role) => <article key={role.id} className="rounded-xl border border-gray-800 bg-gray-950/50 p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-bold text-white">{role.name}</h2><p className="mt-1 text-xs font-mono text-red-400">{role.code}</p></div>{role.isSystem ? <ShieldCheck className="h-5 w-5 text-emerald-400" /> : <button onClick={() => clone(role)} className="text-xs text-blue-400">Sua nhanh</button>}</div><p className="mt-3 text-sm text-gray-400">{role.description}</p><p className="mt-4 text-xs text-gray-500">{role.permissions.includes('*') ? 'Toan quyen' : `${role.permissions.length} quyen`}</p>{role.isSystem ? <button onClick={() => clone(role)} className="mt-4 text-xs text-blue-400 hover:text-blue-300">Clone thanh role tuy chinh</button> : null}</article>)}</div></div>;
}
